ncollide_entities/shape/trimesh.rs
ncollide_procedural/utils.rs
ncollide_transformation/hacd.rs
ncollide_transformation/triangulate.rs
ncollide_utils/data/uid_remap.rs

Update for new entry API

---

ncollide_queries/Cargo.toml

This fixes the build on the latest nightly for me.

Add missing dependencies for ncollide_queries.

---

ncollide_entities/inspection/maybe_as_composite_shape.rs
ncollide_entities/inspection/maybe_as_support_map.rs
ncollide_entities/inspection/repr.rs
ncollide_entities/shape/plane.rs
ncollide_utils/any_private.rs

This fixes the build on the latest nightly for me.

s/std::intrinsics::TypeId/std::any::TypeId

---

ncollide_entities/bounding_volume/aabb.rs
ncollide_entities/bounding_volume/bounding_sphere.rs
ncollide_procedural/path/polyline_path.rs
ncollide_queries/geometry/algorithms/minkowski_sampling.rs
ncollide_queries/geometry/contacts_internal/support_map_against_support_map.rs
ncollide_utils/optimization.rs

To mirror https://github.com/sebcrozet/nalgebra/commit/3107dd607b895a1d4c9e4f6f9ea737b578ac59ac. This fixes the build for me.

Rename x/x_cpy functions to x_mut/x.

---

ncollide_entities/support_map/cuboid_support_map.rs
ncollide_entities/support_map/reflection_support_map.rs
ncollide_pipeline/narrow_phase/composite_shape_repr.rs
ncollide_pipeline/world/collision_world.rs
ncollide_queries/geometry/algorithms/minkowski_sampling.rs
ncollide_queries/geometry/contacts_internal/composite_shape_against_any.rs
ncollide_queries/geometry/distance_internal/composite_shape_against_any.rs
ncollide_queries/geometry/time_of_impact_internal/composite_shape_against_any.rs
ncollide_queries/point/point_compound.rs
ncollide_transformation/hacd.rs

In conjunction with https://github.com/sebcrozet/ncollide/pull/61, this fixes the build for me on the latest rustc.

Updated closure syntax; remove "&mut:" everywhere.

---

ncollide_entities/shape/minkowski_sum.rs

Fixes the build for me along with https://github.com/sebcrozet/nalgebra/pull/90.

Remove IndexMut::Output.

---

ncollide_queries/lib.rs

This fixes the build for me on the 02/12 `rustc`.

Update plugin syntax.

---

ncollide_math/Cargo.toml
ncollide_math/lib.rs
ncollide_utils/Cargo.toml
ncollide_utils/lib.rs
ncollide_utils/optimization.rs

This follows the upstream change in nalgebra.
Fixes #65.

Depend on crates.io rand

---

ncollide_utils/lib.rs
ncollide_utils/triangle.rs

Hello Sébastien,
I tried to play around with 2D convex shapes and noticed that they are not completely supported yet. Then I tried to patch in what's missing and to my surprise succeeded in getting a basic 2D convex demo up and running. Maybe you want to take a look at it, comment and - if everything is ok - merge?
This pull request contains the parts of ncollide.
Michi

extensions for 2D convex shape

---

ncollide_procedural/bezier.rs
ncollide_procedural/utils.rs

This still works on the latest stable.

Fixed compilation on latest nightly.

---

.travis.yml

This updates .travis.yml to test each commit on stable, beta and nightly rust versions.
With this, travis will run a build matrix of 3 builds, to test on the beta, stable, and nightly rust compilers.
Check out the travis build test for this pull request as an example for what this would do.

Update .travis.yml to test on all channels

---

.travis.yml
ncollide_procedural/Cargo.toml
ncollide_queries/Cargo.toml
ncollide_queries/geometry/distance_internal/composite_shape_against_any.rs

Version of rustc: rustc 1.3.0-nightly (cb7d06215 2015-06-26).

Update to the last rust-nightly.

---

ncollide_queries/ray/ray_ball.rs

The normal and uv computations were broken.

Fix a regression on the ray-cast on balls.

---

ncollide_pipeline/broad_phase/dbvt_broad_phase.rs

Prevent division/modulo by zero if the last pair was just removed.

Fix division by zero from #98

---

ncollide_pipeline/world/collision_objects_dispatcher.rs
ncollide_pipeline/world/collision_world.rs
ncollide_pipeline/world/mod.rs
ncollide_transformation/to_polyline/to_polyline.rs

Replace closure by iterators to collect contact pairs and contacts.

---

Cargo.toml
ncollide_pipeline/Cargo.toml
ncollide_pipeline/world/collision_groups.rs

See the comments for the `CollisionGroups` structure for more details on the change.

Improve collision groups.

---

ncollide_pipeline/world/mod.rs

expose interferences publicly

---

ncollide_pipeline/world/collision_world.rs
ncollide_pipeline/world/mod.rs

expose interference structures publicly and improve lifetimes #183 
after all one PR seems ok 2 commit is enough for readability

Improve lifetimes

---

ncollide_geometry/query/point_internal/point_triangle.rs
tests/contact.rs
tests/epa.rs

Fix numerical instability issues for the projection of point on triangle

---

src/pipeline/narrow_phase/contact_generator/convex_polyhedron_convex_polyhedron_manifold_generator.rs
src/query/algorithms/gjk.rs
src/query/ray_internal/ray_plane.rs
src/query/ray_internal/ray_support_map.rs

Properly handle ray parallel to segments.

---

src/shape/convex.rs
src/shape/convex_polygon.rs

Add constructors to ConvexHull/ConvexPolygon that compute the convex hull explicitly.

---

src/shape/triangle.rs

Fix edge FeatureId indexing for triangles.

---

build/ncollide2d/tests/geometry/ray_cast.rs
build/ncollide2d/tests/geometry/time_of_impact2.rs
src/query/algorithms/gjk.rs

Fix some cornercases of ray casting.

---

src/pipeline/broad_phase/dbvt_broad_phase.rs

I was unable to run the ncollide_testbed3d tests due to build errors (not caused by this change).
ncollide_testbed2d passes.

Make DBVTBroadPhase::pairs_to_remove obsolete via HashMap::retain().

---

ncollide_testbed3d/Cargo.toml
publish.sh
src/pipeline/narrow_phase/contact_generator/ball_ball_manifold_generator.rs
src/pipeline/narrow_phase/contact_generator/ball_convex_polyhedron_manifold_generator.rs
src/pipeline/narrow_phase/contact_generator/composite_shape_shape_manifold_generator.rs
src/pipeline/narrow_phase/contact_generator/contact_manifold_generator.rs
src/pipeline/narrow_phase/contact_generator/convex_polyhedron_convex_polyhedron_manifold_generator.rs
src/pipeline/narrow_phase/contact_generator/plane_ball_manifold_generator.rs
src/pipeline/narrow_phase/contact_generator/plane_convex_polyhedron_manifold_generator.rs
src/pipeline/narrow_phase/default_narrow_phase.rs
src/query/contacts_internal/contact_manifold.rs
src/shape/convex_polygon.rs
src/utils/id_allocator.rs

Fix https://github.com/sebcrozet/nphysics/issues/136

Properly deallocate contact ID when a contact manifold generator is removed

---

src/pipeline/narrow_phase/contact_generator/ball_convex_polyhedron_manifold_generator.rs
src/query/point_internal/point_ball.rs
src/query/point_internal/point_plane.rs
src/shape/convex.rs
src/shape/convex_polygon.rs
src/shape/convex_polyhedron.rs
src/shape/cuboid.rs
src/shape/segment.rs
src/shape/triangle.rs

Addresses https://github.com/rustsim/nphysics/issues/148

Properly handle the degenerate ball-vs-polyhedron case where the ball center lies on the polyhedron boundary exactly.

---

build/ncollide3d/tests/geometry/cuboid_ray_cast.rs
build/ncollide3d/tests/geometry/mod.rs
src/query/ray_internal/ray_aabb.rs

Fix AABB ray-cast

---

src/partitioning/dbvt.rs

"boundin" -> "bounding" in dbvt.rs

---

src/pipeline/narrow_phase/contact_generator/ball_convex_polyhedron_manifold_generator.rs
src/pipeline/narrow_phase/contact_generator/plane_ball_manifold_generator.rs
src/pipeline/narrow_phase/contact_generator/plane_convex_polyhedron_manifold_generator.rs

Fix https://github.com/rustsim/nphysics/issues/189

Fix incorrect contact preprocessor application for some shape pairs.

---

src/transformation/hacd.rs

Fix https://github.com/sebcrozet/kiss3d/issues/167

Fix compilation with rust 1.34.

---

src/partitioning/bvt.rs
src/pipeline/world/collision_object.rs
src/pipeline/world/collision_world.rs

Successor of #250, without the CollisionGroup or serialization changes.

Adds some setters to CollisionObject and CollisionWorld

---

src/shape/cuboid.rs

Fix doc about Cuboid's half-extents.

---

src/shape/convex.rs

This could cause some jitters in some contact configuration involving a capsule and a convex-hull shapes.

Fix support feature computation for 3D ConvexHull shape.

---

src/shape/shape.rs

Remove gratuitous indirection from ShapeHandle

---

src/pipeline/object/collision_groups.rs

These bullet points were getting flowed together.

Fix collision group documentation formatting, grammar

---

src/query/algorithms/epa2.rs

This will iteratively search for a direction that lies on the normal cone of each vertex involved in the contact.
Fix #333

EPA2: extract a valid contact normal for the vertex-vertex case.

---

src/query/algorithms/epa2.rs
src/query/algorithms/epa3.rs
src/query/algorithms/gjk.rs
src/query/contact/contact_kinematic.rs
src/query/nonlinear_time_of_impact/nonlinear_time_of_impact_support_map_support_map.rs
src/shape/convex_polygonal_feature3.rs

Remove debug prints.

---

src/pipeline/broad_phase/broad_phase_pair_filter.rs
src/pipeline/glue/update.rs
src/pipeline/object/collision_groups.rs
src/pipeline/world.rs

Meant to be paired with [nphysics#278](https://github.com/dimforge/nphysics/pull/278).
By accepting the handle and the set, it is possible to insert additional information into the filter via the set.

Modify `BroadPhasePairFilter` to accept set

---

src/pipeline/narrow_phase/contact_generator/ball_convex_polyhedron_manifold_generator.rs
src/query/contact/contact_ball_convex_polyhedron.rs

Fix corner case for ball-pointquery collision detection.
