dimforge/ncollide

ncollide_utils/data/hash.rs
ncollide_utils/data/hash_map.rs
ncollide_utils/data/pair.rs
ncollide_utils/data/uid_remap.rs
ncollide_utils/hashable_partial_eq.rs
ncollide_utils/lib.rs

Despite what Travis says, `ncollide` master does not compile with `rustc` master. There were two issues, dealt with in two commits:
- `std::num::UnsignedInt` was deprecated; you can just use its methods now without needing the trait. That was straightforward, in the first commit.
- There is now a `serialize` crate, and `std` objects now derive from it and not from `rustc-serialize`. I went through and changed `rustc-serialize` -> `serialize`, `RustcEncodable` -> `Encodable`, `RustcDecodable` -> `Decodable`.
There are still a large number of deprecation warnings which I did not address, but it does compile.

Update to newer Rust

---

.travis.configure.sh
.travis.yml
ncollide_pipeline/Cargo.toml
ncollide_pipeline/narrow_phase/plane_support_map.rs
ncollide_pipeline/narrow_phase/support_map_support_map.rs
ncollide_queries/Cargo.toml
ncollide_queries/geometry/distance_internal/any_against_any.rs
ncollide_utils/Cargo.toml
ncollide_utils/data/hash_map.rs

This fixed type-inference related errors. Works on stable but not on the nightlies so this looks
like a regression on the compiler-side.
Version of rustc: 1.3.0-nightly (67256dff6 2015-07-09).

Type inference regression? Update to the last rust-nigthly

---

Cargo.toml
ncollide_queries/Cargo.toml
ncollide_queries/ray/ray_ball.rs
ncollide_queries/ray/ray_support_map.rs
tests/ball_ball_toi.rs

While attempting to fix a regression on `nrays` scenes involving balls, I ended up fixing this.
Fix #35.

Fix ball-vs-ball TOI whenever the ray has a non-unit direction.

---

ncollide_entities/Cargo.toml
ncollide_entities/inspection/maybe_as_composite_shape.rs
ncollide_entities/inspection/maybe_as_support_map.rs
ncollide_entities/inspection/mod.rs
ncollide_entities/inspection/repr.rs
ncollide_entities/shape/plane.rs
ncollide_pipeline/Cargo.toml
ncollide_pipeline/narrow_phase/basic_collision_dispatcher.rs
ncollide_pipeline/narrow_phase/collision_detector.rs

This make type inference more available whenever the `Repr` trait is used.
As a side effect, the `BasicCollisionDispatcher` now takes two type parameters `P` and `M` for the point and matrix types.

Add point and matrix type parameters to the `ReprDesc`.

---

ncollide_entities/Cargo.toml
ncollide_entities/bounding_volume/aabb.rs
ncollide_entities/bounding_volume/bounding_sphere.rs
ncollide_entities/bounding_volume/mod.rs

For some reason, the compiler manages to infer types properly using the free functions, while it
fails when the user calls the (HasBoundingSphere and HasAABB) traits' methods directly.
Closes #84.

Add free functions to compute the bounding sphere or box.

---

ncollide_pipeline/world/mod.rs

The types were still private, meaning client code would not be able to use them.

make CollisionWorld{2/3} public

---

Cargo.toml
examples/dbvt_broad_phase2d.rs
examples/dbvt_broad_phase3d.rs
ncollide_pipeline/Cargo.toml
ncollide_pipeline/broad_phase/broad_phase.rs
ncollide_pipeline/broad_phase/dbvt_broad_phase.rs
ncollide_pipeline/tests/collision_world.rs
ncollide_pipeline/world/collision_world.rs
ncollide_utils/Cargo.toml
ncollide_utils/data/hash_map.rs

Objects removal was not handled properly at several places:
* some collision pairs involving deleted objects were not properly removed by the broad phase.
* the collision world removed the collision objects too soon (before the broad phase had a chance to report the proximity loss event).
The solution here is to defer object removal from the collision world until an update is made.
Therefore, the `.remove(...)` method of `CollisionWorld` was renamed to `.deferred_remove(...)`. A new method `.perform_removals_and_broad_phase()` actually applies the removal but, as a side effect, triggers a broad phase update as well.
This fix also renames all the methods including the word `defered` to `deferred` (with two 'r').
Actually fixes #57.

Handle object removal properly

---

ncollide_geometry/shape/shape.rs

Just like `Rc<Box<T>>`, `Arc<Box<T>>` is redundant, since `Arc` already heap-allocates and can constitute a trait object.

Reduce indirection in ShapeHandle internals

---

ncollide_geometry/query/mod.rs
ncollide_geometry/query/point_internal/mod.rs
ncollide_geometry/query/point_internal/point_mesh.rs
ncollide_geometry/query/point_internal/point_query.rs
ncollide_geometry/query/point_internal/point_segment.rs
ncollide_geometry/query/point_internal/point_triangle.rs

This is a continuation of #148, which I closed accidentally.
@sebcrozet, I incorporated the changed you requested. I also played around with the names a bit, and am much happier about them now.
The only name I don't particularly like is `project_point_with_extra_info`, as it's a bit long. I can't think of anything better though. `project_point_with_info` was just plain wrong (The regular `project_point` also returns "info"). `project_point` would be perfect, of course, but would introduce ambiguity and require ugly syntax at call sites.
Closes #147.

Return additional information from a point projection

---

ncollide_geometry/partitioning/dbvt2.rs

when insert a leaf into the dbvt if the leaf come from a removal from
another dbvt tree then its parent field can be whatever so it must be
override.
also we could reset parent to Root when removing a leaf ? that would
be more logical

fix bug in dbvt2

---

build/ncollide2d/tests/geometry/compound_penetration.rs
build/ncollide2d/tests/geometry/mod.rs
src/query/contacts_internal/composite_shape_against_shape.rs

Fix #171.
Maybe related to #209.

Take local compound part transform into account for query::contact computation.

---

src/pipeline/narrow_phase/proximity_detector/composite_shape_shape_proximity_detector.rs

Properly handle the case where the CompositeShapeShapeProximityDetector is flipped.

---

build/ncollide3d/tests/geometry/interferences_with_ray.rs
build/ncollide3d/tests/geometry/mod.rs

I was trying to use `interferences_with_ray` unsuccessfully. After some debugging I realized I needed to call `update` after inserting the objects for them to be found. I added this test to find the problem, and I think it might be useful for more people to have it in the project.

Interferences with ray test

---

src/pipeline/world/collision_groups.rs

"interactinos" -> "interactions"

---

build/ncollide3d/examples/collision_groups.rs
ncollide_testbed2d/examples/bouncing_ball2d.rs
ncollide_testbed3d/examples/bouncing_ball3d.rs
src/pipeline/world/collision_groups.rs

Provides builder-pattern style APIs to CollisionGroups --- a nice alternative  for many use-cases.

Add convenience methods for creating CollisionGroups

---

src/shape/shape.rs

This fixes the nightly build.
The newest nightly supports type_id natively resulting in a name collision.
Once 1.33.0 is stable, the trait 'GetTypeId' should be removed in favour of the native function.

Add workaround for rust issue #27745

---

src/query/ray_internal/ray.rs
src/query/ray_internal/ray_polyline.rs
src/query/ray_internal/ray_support_map.rs
src/shape/polyline.rs
src/shape/trimesh.rs

This also fixes the FeatureId returned when casting a ray on a segment or a polyline.

Implement a special-cases of ray-cast on segment.

---

src/pipeline/narrow_phase/contact_generator/contact_manifold_generator.rs
src/pipeline/world/collision_world.rs

This allows a custom `ContactDispatcher` to be installed, making user-supplied `Shape` impls usable.

 Allow CollisionWorld's NarrowPhase to be replaced 

---

src/bounding_volume/aabb_support_map.rs
src/bounding_volume/aabb_triangle.rs
src/bounding_volume/mod.rs

A relatively long time inside `TriMesh::new` is spent computing AABBs for triangles in the mesh. Solves the problem by rolling a custom AABB function for triangles, which is around three times as fast as using the generic support map implementation.
This could be further improved in the future by providing an AABB function which doesn't take an isometry parameter (as `TriMesh::new` just passes in `Isometry::identity()` anyway), but it would require some API changes that I wasn't sure how to best approach.

Improve triangle AABB performance

---

src/shape/shape.rs

Tested locally and doesn't cause problems when `cargo test` is called.
This would allow ShapeHandle's to be created in cases where the concrete type of the Shape isn't known, allowing the user to pass in their Shapes as trait objects.

Remove extraneous Clone bound on ShapeHandle::new()

---

build/ncollide2d/Cargo.toml
build/ncollide3d/Cargo.toml

The rand crate is only used in benchmarks, so it doesn't need to be a dependency of this crate, but can be a dev-dependency instead. rand is still a transitive dependency of nalgebra, but still, this simplifies the dependency graph a little bit.

Make rand dependency a dev-dependency

---

build/ncollide3d/Cargo.toml
build/ncollide3d/benches/bounding_volume/mod.rs
build/ncollide3d/benches/common/default_gen.rs
build/ncollide3d/benches/common/macros.rs
build/ncollide3d/benches/query/algorithm.rs
build/ncollide3d/benches/query/contacts.rs
build/ncollide3d/benches/query/ray.rs
build/ncollide3d/benches/support_map/mod.rs

Fixes compilation of the benchmarks. Additionally, resolves deprecation warnings from the nalgebra and rand crates. As a sidenote, I think we could be able to avoid the additional dependency to rand_isaac by switching to another random number generator, such as `XorShiftRng`.

Fix benchmarks

---

src/query/algorithms/gjk.rs
src/query/mod.rs
src/query/ray_internal/mod.rs
src/query/ray_internal/ray_ball.rs
src/query/time_of_impact_internal/ball_against_ball.rs
src/query/time_of_impact_internal/composite_shape_against_shape.rs
src/query/time_of_impact_internal/mod.rs
src/query/time_of_impact_internal/plane_against_support_map.rs
src/query/time_of_impact_internal/shape_against_shape.rs
src/query/time_of_impact_internal/support_map_against_support_map.rs
src/query/time_of_impact_internal/time_of_impact_with.rs

Resolves #34. Provides an additional `query::time_of_impact_and_normal` function which returns the contact normal in addition to the time of impact. I decided to make this into a new function in order to avoid a breaking change. In the future it might make sense to combine these two functions into a single function that returns a struct, perhaps similar to the existing `RayIntersection` struct. Please let me know if any of this needs changing to accommodate a different design or whatnot.

Return the contact normal as a result of TOI computation

---

src/pipeline/object/collision_object_set.rs
src/pipeline/world.rs

Because the collision world did not clear the collision object flags automatically, it could end up re-computing contacts between everything at each frame.

Fix significant performance regression on the CollisionWorld

---

src/shape/segment.rs

The lack of clear did break 3D come collision detections with segments (which includes collision detection with capsules).

Segment::support_face_toward: clear the output buffer before filling it.

---

src/pipeline/broad_phase/dbvt_broad_phase.rs

Previously contacts would not be removed (and would seem to persist forever) if collision groups or filters were modified to disallow the contact.
This (rustsim/nphysics#55) indicates that this should take significantly more work, but it seems that all the logic was already there and the check to remove contacts was incorrect.
Should fix rustsim/nphysics#55 and fix #164.

Allow updating collider collision rules.

---

src/shape/trimesh.rs

`an_array.into_iter()` currently just works because of the autoref
feature, which then calls `<[T] as IntoIterator>::into_iter`. But
in the future, arrays will implement `IntoIterator`, too. In order
to avoid problems in the future, the call is replaced by `iter()`
which is shorter and more explicit.
A crater run showed that your crate is affected by a potential future 
change. See https://github.com/rust-lang/rust/pull/65819 for more information.

Use `slice::iter` instead of `into_iter` to avoid future breakage

---

src/query/point/point_aabb.rs

The projection was wrong in the specific case where:
- The point is inside of the AABB/Cuboid.
- The projection being performed is non-solid.
- The closest face to the point is the one with normal `-x`.
In this situation, the computed projection point wrong due to a flipped sign.

Fix point/aabb projection along the x axis when the point is inside of the AABB.

---

build/ncollide2d/examples/first_ray_intersect.rs
src/partitioning/bvh.rs
src/pipeline/broad_phase/broad_phase.rs
src/pipeline/broad_phase/dbvt_broad_phase.rs
src/pipeline/glue/mod.rs
src/pipeline/glue/query.rs
src/pipeline/world.rs
src/query/visitors/first_ray_interference_visitor.rs
src/query/visitors/mod.rs
src/query/visitors/ray_intersection_cost_fn_visitor.rs

This PR adds a new method to the `CollisionWorld` for detecting the first ray intersection with an object.
It creates a new visitor called `RayIntersectionCostFnVisitor` which takes in a cost function and applies it for each leaf node in the BVH using the data contained. This visitor is relatively generic and can be used for other cost functions applied to a `BroadPhase`.
The `.first_intersection_with_ray()` method passes in the equivalent of a narrow phase as the cost function which finds the smallest `toi` in the tree.
- There are a few TODO's left in comments that mainly involve traits being more restrictive than I would like. It should be possible to make them more open in the future without a major interface change so maybe not blocking?
- I would like to add a minimum and maximum to …

First interference with ray

---

src/pipeline/object/collision_groups.rs

I added an option to the api to set the bit masks directly, this change wouldn't / shouldn't move the api boundary as it's always possible to convert the masks into array on the library side if the collision group system gets changed.

extend api with mask option

---

build/ncollide3d/tests/geometry/first_interference_with_ray.rs
build/ncollide3d/tests/geometry/mod.rs
src/partitioning/bvh.rs
src/query/visitors/ray_intersection_cost_fn_visitor.rs

Trying to familiarize myself with the library, I spent some time trying to understand best_first_search so commented and cleaned it up a bit. Only a slight functional change, where previously leaf nodes would be added to the heap then immediately popped and discarded.
Additionally, add simple testcase for first_interference_with_ray, based on interferences_with_ray.

Comment & clean up best_first_search, add testcase

---

build/ncollide2d/Cargo.toml
build/ncollide3d/Cargo.toml
src/query/algorithms/epa3.rs
src/query/algorithms/gjk.rs
src/query/closest_points/closest_points_ball_ball.rs
src/query/contact/contact_ball_ball.rs
src/query/point/point_tetrahedron.rs
src/query/point/point_triangle.rs
src/transformation/convex_hull3.rs

This PR adds some tweaks to various collision-detection methods in order to improve their behavior when using fixed-point numbers. Because some of these modification may have a (slightly) negative performance impact, they are only enabled when the `improved_fixed_point_support` feature of ncollide is enabled.
In order to use ncollide with fixed-point numbers, it is strongly recommented to use at least 24 bits for the decimal part. Less accuracy may result in systematic failure of some algorithms.

Add some tweaks to improve robustness when using fixed-point numbers.

---

build/ncollide2d/examples/time_of_impact_query2d.rs
build/ncollide2d/tests/geometry/ball_ball_toi.rs
build/ncollide2d/tests/geometry/time_of_impact2.rs
build/ncollide3d/examples/time_of_impact_query3d.rs
build/ncollide3d/tests/geometry/ball_ball_toi.rs
build/ncollide3d/tests/geometry/ball_triangle_toi.rs
build/ncollide3d/tests/geometry/still_objects_toi.rs
build/ncollide3d/tests/geometry/time_of_impact3.rs
build/ncollide3d/tests/geometry/trimesh_trimesh_toi.rs
src/pipeline/world.rs
src/query/error.rs
src/query/mod.rs
src/query/nonlinear_time_of_impact/nonlinear_time_of_impact.rs
src/query/nonlinear_time_of_impact/nonlinear_time_of_impact_composite_shape_shape.rs
src/query/time_of_impact/time_of_impact.rs
src/query/time_of_impact/time_of_impact_composite_shape_shape.rs
src/query/toi_dispatcher.rs

This provides a foundation for nphysics to support CCD on custom shapes, and for downstream crates to conveniently compose dispatchers. This requirement is motivated by my work in [planetmap](https://github.com/Ralith/planetmap) to provide collision detection for streaming spherical terrain, which requires close integration with ncollide queries to be efficient, much like heightfields do.
While this could be merged as-is, there's one question I'd like feedback on: should we fold `ContactDispatcher` and `ProximityDispatcher` into this trait? A single trait object is more convenient (particularly for composition), and in general anyone seeking to implement a custom shape will probably want to support everything, or at least be fully conscious of any unsupported operations.

Dynamic dispatch helper for time-of-impact queries

---

src/pipeline/object/collision_groups.rs

This should make it easier to create `CollisionGroups` values from scratch using bitmasks. This is a further extension of #331.

Add empty CollisionGroups ctor, and option to replace masks entirely

---

src/shape/trimesh.rs

Similar to #327 but also recalculate on transform*() methods. The method is line for line identical to royalmustard's implementation, which I understand is drawn from the constructor, but if that is a problem then I welcome any advice on how to fix it.

Recalc aabb on transform as well as scale

---

src/pipeline/broad_phase/broad_phase_pair_filter.rs
src/pipeline/world.rs

An update on #359 to finish the implementation of [nphysics#278][1].
Removing the `Any` bound allows for non-`'static` sets, meaning the filter can use borrowed body and collider sets.
[1]: https://github.com/dimforge/nphysics/pull/278

Remove `Any` bound from BPPF

---

src/query/point/point_trimesh.rs

Was previously just `unimplemented!()`.

Implement TriMesh::project_point_with_feature

---

src/shape/mod.rs

All of these are useful for inspecting the structure of a mesh, in particular
combined with `FeatureId`.
Fixes #347

Expose TriMeshEdge, TriMeshVertex, FaceAdjacentToEdge

---

src/pipeline/object/collision_object_set.rs

Allow user to change CollisionObjectSlab's capacity.

Capacity api for CollisionObjectSlab

---

src/shape/convex.rs

When simplifying coplanar or concave triangles into a single polygonal
face, sometimes the edge-marching algorithm will create a face with two
vertices, throwing off the Euler characteristic for the resulting solid.
Adding a guard against these degenerate faces keeps the Euler
characteristic correct.

`ConvexHull::try_new`: avoid adding degenerate faces

---

build/ncollide2d/Cargo.toml
build/ncollide3d/Cargo.toml
publish.sh
src/interpolation/rigid_motion.rs
src/pipeline/narrow_phase/contact_generator/ball_convex_polyhedron_manifold_generator.rs
src/query/algorithms/epa3.rs
src/query/closest_points/closest_points_segment_segment.rs
src/query/closest_points/mod.rs
src/query/nonlinear_time_of_impact/nonlinear_time_of_impact_support_map_support_map.rs
src/query/point/point_query.rs
src/query/ray/ray_support_map.rs
src/query/time_of_impact/time_of_impact.rs
src/query/time_of_impact/time_of_impact_plane_support_map.rs
src/shape/capsule.rs
src/shape/cone.rs
src/shape/convex.rs
src/shape/convex_polygon.rs
src/shape/convex_polygonal_feature2.rs
src/shape/convex_polygonal_feature3.rs
src/shape/cuboid.rs
src/shape/cylinder.rs
src/shape/segment.rs
src/shape/shape_impl.rs
src/shape/trimesh.rs

This updates all the dependencies of ncollide to their latest versions.
In addition this:
- Fix a bug in the 3D EPA implementation that could cause an assertion failure.
- Add a segment-segment closest point computation that allow specification of the epsilon used for detecting quasi-parallel cases.
- Add a `RayCast` implementation for 2D triangles.
- Fix all the calls to `copysign` after the update to `simba` 0.3.0.

Update deps + minor feature additions and fixes
